### ISSUE TITLE
module 'logging' has no attribute 'StreamHandler'

### ISSUE THREAD

**Issue by Morteza-M-Saber** [cbg-ethz/NGS-pipe#1]
When running the program on desktop or linux using the command:
python3 /path/to/snakemake/bin/snakemake -s prepare_data.snake

The following error appears:

Traceback (most recent call last):
  File "/home/masih/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/masih/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/snakemake_install/snakemake/snakemake/__main__.py", line 2, in <module>
    from snakemake import main
  File "/home/masih/miniconda3/lib/python3.6/site-packages/snakemake/__init__.py", line 11, in <module>
    import logging as _logging
  File "/lustre4/home/masih/projects/pipeline_design_tutorial/snakemake_install/snakemake/snakemake/logging.py", line 20, in <module>
    class ColorizingStreamHandler(_logging.StreamHandler):
AttributeError: module 'logging' has no attribute 'StreamHandler'

**Comment by singerj** [comment]
Hi @Morteza-M-Saber,

Try /path/to/snakemake/bin/snakemake -s prepare_data.snake instead. It seem you have installed snakemake via miniconda such that it will already use the appropriate python distribution. By writing python3 /path/to/snakemake/bin/snakemake you force snakemake to use a different python distribution. 

Also make sure that no PYTHONPATH is set.

We will update the documentation accordingly.

I will close this issue, however, if you continue to have problems we will reopen it.

Best,
Jochen

**Comment by Morteza-M-Saber** [comment]
Hi Jochen

Thanks for the correction. It is fine now.
Just to mention that,  just snakemake -s prepare_data.snake would work via miniconda snakemake and no /path/to/snakemake/bin/snakemake  is needed.

Yours,
Morteza
